- project:
    check:
      jobs:
        - ara-server-ansible-integration:
            voting: false
        - tox-format
        - tox-py35
        - tox-pep8
    gate:
      jobs:
        - tox-format
        - tox-py35
        - tox-pep8
