- project:
    vars:
      rtd_webhook_id: '49230'
    templates:
      - docs-on-readthedocs
    check:
      jobs:
        - ara-integration-fedora-2.7
        - ara-integration-fedora-devel:
            voting: false
        - ara-integration-ubuntu-2.6
        - ara-tox-linters
        - ara-tox-py3
    gate:
      jobs:
        - ara-integration-fedora-2.7
        - ara-integration-ubuntu-2.6
        - ara-tox-linters
        - ara-tox-py3
