- project:
    vars:
      rtd_webhook_id: '49230'
    templates:
      - docs-on-readthedocs
    check:
      jobs:
        - ara-server-ansible-integration:
            voting: false
        - ara-tox-linters
        - ara-tox-py3
    gate:
      jobs:
        - ara-tox-linters
        - ara-tox-py3
