- project:
    check:
      jobs:
        - ara-server-ansible-integration
        - tox-py35
        - tox-pep8
    gate:
      jobs:
        - ara-server-ansible-integration
        - tox-py35
        - tox-pep8
